server:
  port: 8080
  servlet:
    encoding:
      force-response: true # 强制使用 UTF-8 编码
      charset: UTF-8
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://${solace.datasource.host}:${solace.datasource.port}/${solace.datasource.database}
    username: ${solace.datasource.username}
    password: ${solace.datasource.password}
    driver-class-name: ${solace.datasource.driver-class-name}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      # 避免在容器尚未完全可用时访问元数据（可选）
      hibernate.boot.allow_jdbc_metadata_access: true
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.solaceisle.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      solaceisle:
        mapper: debug
        service: info
        controller: info

#knife4j配置
springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: false
  production: false
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
solace:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: ${solace.jwt.user-secret-key}
    # 设置jwt过期时间
    user-ttl: ${solace.jwt.user-ttl}
    # 设置前端传递过来的令牌名称
    user-token-name: ${solace.jwt.user-token-name}
