solace:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: 5b8f9090c47ebe1f097c78dba13c895c72a87c30356bdacc1b5fdf1937b1c6c9
    # 设置jwt过期时间
    user-ttl: 600000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: solace_isle
    username: postgres
    password: zl20050805666
  mail:
    host: 'smtp.qq.com'
    port: 587
    username: zhangle666699@qq.com
    password: pianvmbxpesodccb
    from: zhangle666699@qq.com
  hotline: 114514-1919810
